#!/usr/bin/sh

# lazy script for I JUST WANNA RUN MY PROGRAM RIGHT NOW!!!!

./configure --prefix="$(pwd)/build/root" 1>/proc/self/fd/2
cd build
./gen 1>/proc/self/fd/2
./gen install 1>/proc/self/fd/2
./root/bin/* $@ # this will run every single binary, which is pretty bad ;(.  dont forget to change this line
